apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: django-app
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/acme/db-app
  version:
    semver: v1.0.0
  repository:
    url: ghcr.io/mohammad-ammar14
    secretRef:
      name: creds
  verify:
  - name: ammar
    publicKey:
      secretRef:
        name: ammar-publickey
